---
permalink: /publications
title: "Recent publications"
output:
  md_document:
    variant: gfm
    preserve_yaml: TRUE
    toc: TRUE
    toc_depth: 3
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile,
    encoding = encoding,
    output_dir = "../_pages") })
always_allow_html: true
excerpt: "Publications"
author_profile: true
redirect_from: 
  - /publications/
  - /publications.html
---

# Recent publications

A selection of recent publications are included here. My google scholar indexed publications can be found [here](https://scholar.google.com/citations?user=p6WxMVwAAAAJ&hl=en&oi=ao).

## Pseudogenes and intrinsic error in genomic data

* [Publication link](https://link.springer.com/article/10.1186/s12864-024-10137-0)
* [Github repo of plots and results](https://github.com/npcooley/Pseudogenes)

Modern genomic annotation pipelines like [PGAP](https://www.ncbi.nlm.nih.gov/refseq/annotation_prok/) and [EGAP](https://www.ncbi.nlm.nih.gov/refseq/annotation_euk/process/) provide features annotated as **pseudogenes**. What these annotations realistically represent ends up being partially dependent upon the technologies used to generate the source sequence data and the strategies used to assemble the genomic data being annotated. Meaning pseudogenizations, from the perspective annotations can represent either a true recent mutation causing loss or modulation of function in a clearly identifiable feature, or a sequencing or assembly error that have been incorporated in the assembled genomic data.

## Functional classification of protein coding sequences

* [Publication link](https://academic.oup.com/nargab/article/3/3/lqab080/6371227)
* [Github repo of plots and results](https://github.com/npcooley/AAClassification)

Accurate classification of protein coding sequences is difficult. A functional classifier based on the previously existing taxonomic classifier [IDTAXA](https://decipher.codes/Classification.html) was developed was an emphasis on specificity. Benchmarking classification strategies with misclassication and overclassification rates provide a clear picture of the strengths and weaknesses of different methods.


